- hosts: miner-post
  remote_user: cs
  environment:
    RUST_LOG: trace
    RUST_BACKTRACE: full
    FIL_PROOFS_PARAMETER_CACHE: '{{ fil_proofs_param_path }}'
    FIL_PROOFS_MAXIMIZE_CACHING: '{{ fil_proofs_maximize_caching }}'
    FIL_PROOFS_USE_GPU_COLUMN_BUILDER: '{{ fil_proofs_use_gpu_column_builder }}'
    FIL_PROOFS_USE_GPU_TREE_BUILDER: '{{ fil_proofs_use_gpu_tree_builder }}'
    LOTUS_PATH: '{{ lotus_path }}'
    LOTUS_STORAGE_PATH: '{{ lotus_storage_path }}'
    WORKER_PATH: '{{ lotus_worker_path }}'
    FULLNODE_API_INFO: '{{ fullnode_api_info }}'
  tasks:
    - name: Start lotus daemon
      shell: |
        tmux new -s lotus -d -n daemon
        tmux send-keys -t lotus:daemon "lotus daemon" C-m
