- hosts: lotus-post-miner
  remote_user: cs
  environment:
    RUST_LOG: trace
    RUST_BACKTRACE: full
    FIL_PROOFS_PARAMETER_CACHE: '{{ fil_proofs_param_path }}'
    FIL_PROOFS_MAXIMIZE_CACHING: '{{ fil_proofs_maximize_caching }}'
    FIL_PROOFS_USE_GPU_COLUMN_BUILDER: '{{ fil_proofs_use_gpu_column_builder }}'
    FIL_PROOFS_USE_GPU_TREE_BUILDER: '{{ fil_proofs_use_gpu_tree_builder }}'
    LOTUS_PATH: '{{ lotus_path }}'
    LOTUS_STORAGE_PATH: '{{ lotus_storage_path }}'
    WORKER_PATH: '{{ lotus_worker_path }}'
  vars:
    - post_miner_host: 192.168.200.61
    - post_miner_port: 1357
  tasks:
    - name: Start post miner
      shell: |
        tmux new-window -t lotus:1 -n miner
        tmux send-keys -t lotus:miner "ulimit -n 65535" C-m
        tmux send-keys -t lotus:miner "lotus-miner run --post=true --p2p=false --sctype=alloce --sclisten={{ post_miner_host }}:{{ post_miner_port }}" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-post-miner-`date +%Y-%m-%d-%H-%M`.log"
