- hosts: lotus-seal-worker-precommit
  remote_user: cs
  environment:
    RUST_LOG: trace
    RUST_BACKTRACE: full
    FIL_PROOFS_PARAMETER_CACHE: '{{ fil_proofs_param_path }}'
    FIL_PROOFS_MAXIMIZE_CACHING: '{{ fil_proofs_maximize_caching }}'
    FIL_PROOFS_USE_GPU_COLUMN_BUILDER: '{{ fil_proofs_use_gpu_column_builder }}'
    FIL_PROOFS_USE_GPU_TREE_BUILDER: '{{ fil_proofs_use_gpu_tree_builder }}'
    FIL_PROOFS_USE_MULTICORE_SDR: '{{ fil_proofs_use_multicore_sdr }}'
    LOTUS_PATH: '{{ lotus_path }}'
    LOTUS_STORAGE_PATH: '{{ lotus_storage_path }}'
    WORKER_PATH: '{{ lotus_worker_path }}'
    MINER_API_INFO: '{{ miner_api_token }}:/ip4/192.168.200.62/tcp/2345/http'
  vars:
    - workspace: '/home/cs/workspace'
    - worker_port: 3456
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_hostname
    - debug: var=lotus_storage_path

    - name: Remove old storage, worker path
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '/home/cs/disk_md0/starstorage'
        - '/home/cs/disk_md0/starworker'
        - '/home/cs/disk_md0/lotusstorage'
        - '/home/cs/disk_md0/lotusworker'

    - name: Create lotus storage, lotus worker and log path
      file:
        path: "{{ item }}"
        state: directory
        owner: cs
        group: cs
        mode: u=rwxr,g=xr,o=x
      loop:
        - '{{ lotus_storage_path }}'
        - '{{ lotus_worker_path }}'
        - '{{ log_path }}'

    - name: Copy myscheduler config to worker
      copy:
        src: '{{ workspace }}/lotus-deploy/config/myscheduler-precommit.json'
        dest: '{{ lotus_worker_path }}/myscheduler.json'

    - name: Start lotus deal worker
      shell: |
        tmux new -s lotus -d -n worker
        tmux send-keys -t lotus:worker "lotus-worker run --listen {{ ansible_default_ipv4.address }}:{{ worker_port }}" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker-`date +%Y-%m-%d-%H-%M`.log"

############################################ seal worker commit ############################################

- hosts: lotus-seal-worker-commit
  remote_user: cs
  environment:
    RUST_LOG: trace
    RUST_BACKTRACE: full
    FIL_PROOFS_PARAMETER_CACHE: '{{ fil_proofs_param_path }}'
    FIL_PROOFS_MAXIMIZE_CACHING: '{{ fil_proofs_maximize_caching }}'
    FIL_PROOFS_USE_GPU_COLUMN_BUILDER: '{{ fil_proofs_use_gpu_column_builder }}'
    FIL_PROOFS_USE_GPU_TREE_BUILDER: '{{ fil_proofs_use_gpu_tree_builder }}'
    LOTUS_PATH: '{{ lotus_path }}'
    LOTUS_STORAGE_PATH: '{{ lotus_storage_path }}'
    MINER_API_INFO: '{{ miner_api_token }}:/ip4/192.168.200.62/tcp/2345/http'
  vars:
    - worker_port0: 3450
    - worker_port1: 3451
    - worker_port2: 3452
    - workspace: '/home/cs/workspace'
    - storage_path: /home/cs/disk_md0
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_hostname
    - debug: var=lotus_storage_path

    # - name: Create lotus storage, lotus worker and log path
    #   file:
    #     path: "{{ item }}"
    #     state: directory
    #     owner: cs
    #     group: cs
    #     mode: u=rwxr,g=xr,o=x
    #   loop:
    #     - '{{ lotus_storage_path }}'
    #     - '{{ lotus_worker_path }}'
    #     - '{{ log_path }}'

    # - name: Create tmp dir
    #   file:
    #     path: "{{ item }}"
    #     state: directory
    #     owner: cs
    #     group: cs
    #     mode: u=rwxr,g=xr,o=x
    #   loop:
    #     - '{{ storage_path }}/tmp/tmp0'
    #     - '{{ storage_path }}/tmp/tmp1'
    #     - '{{ storage_path }}/tmp/tmp2'
    #     - '{{ storage_path }}/tmp/tmp3'

    # - name: Create lotus storage, lotus worker and log path
    #   file:
    #     path: "{{ item }}"
    #     state: directory
    #     owner: cs
    #     group: cs
    #     mode: u=rwxr,g=xr,o=x
    #   loop:
    #     - '{{ lotus_storage_path }}'
    #     - '{{ lotus_worker_path }}'
    #     - '{{ log_path }}'

    - name: Copy myscheduler config to commit worker
      copy:
        src: '{{ workspace }}/lotus-deploy/config/myscheduler-commit.json'
        dest: '{{ lotus_worker_path }}/myscheduler.json'

    - name: Start lotus seal commit worker 0
      shell: |
        tmux new -s lotus -d -n worker0
        tmux send-keys -t lotus:worker0 "export WORKER_PATH={{ storage_path }}/lotusworker0" C-m
        tmux send-keys -t lotus:worker0 "export CUDA_VISIBLE_DEVICES=0" C-m
        tmux send-keys -t lotus:worker0 "export TMPDIR={{ storage_path }}/tmp/tmp0" C-m
        tmux send-keys -t lotus:worker0 "lotus-worker run --listen={{ ansible_default_ipv4.address }}:{{ worker_port0 }}" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker0-`date +%Y-%m-%d-%H-%M`.log"

    - name: Start lotus seal commit worker 1
      shell: |
        tmux new-window -t lotus -n worker1
        tmux send-keys -t lotus:worker1 "export WORKER_PATH=/home/cs/disk_md0/lotusworker1" C-m
        tmux send-keys -t lotus:worker1 "export CUDA_VISIBLE_DEVICES=1" C-m
        tmux send-keys -t lotus:worker1 "export TMPDIR=/home/cs/disk_md0/tmp/tmp1" C-m
        tmux send-keys -t lotus:worker1 "lotus-worker run --listen={{ ansible_default_ipv4.address }}:{{ worker_port1 }}" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker1-`date +%Y-%m-%d-%H-%M`.log"

    - name: Start lotus seal commit worker 2
      shell: |
        tmux new-window -t lotus -n worker2
        tmux send-keys -t lotus:worker2 "export WORKER_PATH=/home/cs/disk_md0/lotusworker2" C-m
        tmux send-keys -t lotus:worker2 "export CUDA_VISIBLE_DEVICES=2" C-m
        tmux send-keys -t lotus:worker2 "export TMPDIR=/home/cs/disk_md0/tmp/tmp2" C-m
        tmux send-keys -t lotus:worker2 "lotus-worker run --listen={{ ansible_default_ipv4.address }}:{{ worker_port2 }}" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker2-`date +%Y-%m-%d-%H-%M`.log"
