- hosts: lotus-seal-worker
  remote_user: cs
  environment:
    RUST_LOG: trace
    RUST_BACKTRACE: full
    FIL_PROOFS_PARAMETER_CACHE: '{{ fil_proofs_param_path }}'
    FIL_PROOFS_PARENT_CACHE: '{{ fil_proofs_parent_cache }}'
    FIL_PROOFS_MAXIMIZE_CACHING: '{{ fil_proofs_maximize_caching }}'
    FIL_PROOFS_USE_GPU_COLUMN_BUILDER: '{{ fil_proofs_use_gpu_column_builder }}'
    FIL_PROOFS_USE_GPU_TREE_BUILDER: '{{ fil_proofs_use_gpu_tree_builder }}'
    LOTUS_PATH: '{{ lotus_path }}'
    LOTUS_MINER_PATH: '{{ lotus_miner_path }}'
    WORKER_PATH: '{{ lotus_worker_path }}'
    MINER_API_INFO: '{{ miner_api_token }}:/ip4/192.168.200.62/tcp/2345/http'
  vars:
    - workspace: '/home/cs/workspace'
    - worker_port: 3456
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_hostname
    - debug: var=lotus_storage_path

    - name: Create lotus storage, lotus worker, log path, cache path
      file:
        path: "{{ item }}"
        state: directory
        owner: cs
        group: cs
        mode: u=rwxr,g=xr,o=x
      loop:
        - '{{ fil_proofs_parent_cache }}'
        - '{{ lotus_storage_path }}'
        - '{{ lotus_worker_path }}'
        - '{{ log_path }}'

    - name: Copy myscheduler config to worker
      copy:
        src: '{{ workspace }}/lotus-deploy/config/myscheduler-deal-worker.json'
        dest: '{{ lotus_worker_path }}/myscheduler.json'

    - name: Start lotus deal worker
      shell: |
        tmux new -s lotus -d -n worker
        tmux send-keys -t lotus:worker "lotus-worker run --listen {{ ansible_default_ipv4.address }}:{{ worker_port }}  --commit=false" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/lotus-worker-`date +%Y-%m-%d-%H-%M`.log"
