- hosts: seal-miner,window-post-miner,winning-post-miner
  remote_user: '{{ remote_user }}'
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - debug: var=ansible_hostname

    - name: Install inotify-tools
      shell: |
        sudo apt install inotify-tools

    - name: Copy backup script to miner
      copy:
        src: '{{ workspace }}/lotus-ops/scripts/backup-miner.sh'
        dest: '{{ workspace }}/scripts'
        mode: +x

    - name: Start backup miner
      shell: |
        tmux new-window -t lotus:1 -n backup
        tmux send-keys -t lotus:backup "{{ workspace }}/scripts/backup-miner.sh {{ lotus_miner_path }} {{ backup_path }}/{{ ansible_hostname }} {{ backup_user }} {{ backup_host }}" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/backup-`date +%Y-%m-%d-%H-%M`.log"