- hosts: seal-miner
  remote_user: '{{ remote_user }}'
  environment:
    FIL_PROOFS_PARAMETER_CACHE: '{{ fil_proofs_parameter_cache }}'
    LOTUS_PATH: '{{ lotus_path }}'
    LOTUS_MINER_PATH: '{{ lotus_miner_path }}'
  tasks:
    - debug: var=fil_proofs_parameter_cache
    - debug: var=owner

    - name: Init miner
      shell: |
        lotus-miner init --owner={{ owner }} --sector-size=32GiB
