- hosts: worker64
  remote_user: '{{ remote_user }}'
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create workspace directory
      file:
        path: '{{ workspace }}'
        state: directory

    - name: Copy node exporter script to remote server
      copy:
        src: '{{ workspace }}/lotus-ops/scripts/install-node-exporter.sh'
        dest: '{{ workspace }}'
        owner: root
        group: root
        mode: +x

    - name: Copy node exporter service to remote server
      copy:
        src: '{{ workspace }}/lotus-ops/service/node-exporter.service'
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: +x

    - name: Install node exporter
      shell: '{{ workspace }}/install-node-exporter.sh'
