- hosts: precommit-worker,commit-worker
  remote_user: '{{ remote_user }}'
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - debug: var=ansible_all_ipv4_addresses

    - name: Reboot
      shell: 'reboot'
