- hosts: precommit-worker
  remote_user: '{{ remote_user }}'
  environment:
    RUST_LOG: '{{ rust_log }}'
    RUST_BACKTRACE: '{{ rust_backtrace }}'
    FIL_PROOFS_PARAMETER_CACHE: '{{ fil_proofs_parameter_cache }}'
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_all_ipv4_addresses[1]
    - debug: var=ansible_hostname

    - name: Start benchmark
      shell: |
        tmux new -s lotus -d -n bench
        tmux send-keys -t lotus:bench "env FIL_PROOFS_USE_MULTICORE_SDR=1 FIL_PROOFS_MULTICORE_SDR_PRODUCERS=1 NUM_HANDLES=15 NUM_KERNELS=2 ENV_CPU_CORE_BEGIN_NUM=0 ENV_CPU_CORE_END_NUM=8 lotus-bench sealing --sector-size 32GiB --skip-unseal --storage-dir /home/caslx/disk_md0" C-m
        tmux pipe-pane -o "cat >>{{ log_path }}/bench-`date +%Y-%m-%d-%H-%M`.log"