- hosts: worker-precommit
  remote_user: '{{ remote_user }}'
  tasks:
    - debug: var=ansible_all_ipv4_addresses

    - name: Kill commit worker window
      shell: 'tmux kill-window -t lotus:worker{{item}}'
      loop:
        - 0
        - 1
