- hosts: precommit-worker
  remote_user: '{{ remote_user }}'
  become: yes
  become_user: root
  become_method: sudo
  environment:
    WORKER_PATH: '{{ workspace }}'
  vars:
    - workspace: '/home/cs/workspace'
  tasks:
    - name: Copy myscheduler config to worker
      copy:
        src: '{{ workspace }}/lotus-ops/config/myscheduler-precommit.json'
        dest: '{{ lotus_worker_path }}/myscheduler.json'
